version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    target-branch: "dev"
    cooldown:
      default-days: 1
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    target-branch: "dev"
    cooldown:
      default-days: 1
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/apps/mobile"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    target-branch: "dev"
    cooldown:
      default-days: 1
    groups:
      pub-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/apps/server"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    target-branch: "dev"
    cooldown:
      default-days: 1
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/apps/ai"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    target-branch: "dev"
    cooldown:
      default-days: 1
    groups:
      pip-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories:
      - "/apps/server"
      - "/apps/server/postgres"
      - "/apps/ai"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    target-branch: "dev"
    cooldown:
      default-days: 1
    groups:
      docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    target-branch: "dev"
    cooldown:
      default-days: 1
    groups:
      docker-compose-dependencies:
        patterns:
          - "*"
