import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:video_player/video_player.dart';

// ─── Landmark indices (mirrors pose_analysis.py LM class) ──────
class _LM {
  static const lShoulder = 11;
  static const rShoulder = 12;
  static const lElbow = 13;
  static const rElbow = 14;
  static const lWrist = 15;
  static const rWrist = 16;
  static const lHip = 23;
  static const rHip = 24;
  static const lKnee = 25;
  static const rKnee = 26;
  static const lAnkle = 27;
  static const rAnkle = 28;

  static const names = {
    11: 'Épaule G',
    12: 'Épaule D',
    13: 'Coude G',
    14: 'Coude D',
    15: 'Poignet G',
    16: 'Poignet D',
    23: 'Hanche G',
    24: 'Hanche D',
    25: 'Genou G',
    26: 'Genou D',
    27: 'Cheville G',
    28: 'Cheville D',
  };

  static const connections = [
    (_LM.lShoulder, _LM.rShoulder),
    (_LM.lShoulder, _LM.lElbow),
    (_LM.lElbow, _LM.lWrist),
    (_LM.rShoulder, _LM.rElbow),
    (_LM.rElbow, _LM.rWrist),
    (_LM.lShoulder, _LM.lHip),
    (_LM.rShoulder, _LM.rHip),
    (_LM.lHip, _LM.rHip),
    (_LM.lHip, _LM.lKnee),
    (_LM.lKnee, _LM.lAnkle),
    (_LM.rHip, _LM.rKnee),
    (_LM.rKnee, _LM.rAnkle),
  ];
}

// ─── Data model ─────────────────────────────────────────────────
class _FrameData {
  final int frameIndex;
  final int timestampMs;
  final bool poseDetected;
  final Map<int, Offset> landmarks; // key = LM id, value = (x, y) normalised
  final Map<int, double> angles; // key = LM id of joint

  const _FrameData({
    required this.frameIndex,
    required this.timestampMs,
    required this.poseDetected,
    required this.landmarks,
    required this.angles,
  });

  static _FrameData fromJson(Map<String, dynamic> json) {
    final landmarks = <int, Offset>{};
    final rawLm = json['landmarks'] as Map<String, dynamic>? ?? {};
    for (final e in rawLm.entries) {
      final id = int.tryParse(e.key);
      if (id == null) continue;
      final v = e.value as Map<String, dynamic>;
      landmarks[id] = Offset(
        (v['x'] as num).toDouble(),
        (v['y'] as num).toDouble(),
      );
    }

    final angles = <int, double>{};
    final rawAng = json['angles'] as Map<String, dynamic>? ?? {};
    for (final e in rawAng.entries) {
      final id = int.tryParse(e.key);
      if (id == null) continue;
      angles[id] = (e.value as num).toDouble();
    }

    return _FrameData(
      frameIndex: (json['frame'] as int?) ?? 0,
      timestampMs: (json['timestamp_ms'] as int?) ?? 0,
      poseDetected: (json['pose_detected'] as bool?) ?? false,
      landmarks: landmarks,
      angles: angles,
    );
  }
}

// ─── Page ────────────────────────────────────────────────────────
class AnalysisViewPage extends StatefulWidget {
  /// The raw `result_json` string returned by the server.
  final String resultJson;

  /// Optional processing time for the header.
  final int? processingMs;

  /// The local video file to show under the skeleton overlay.
  final File? videoFile;

  /// Markdown coaching hints generated by Gemini (null if unavailable).
  final String? hints;

  const AnalysisViewPage({
    super.key,
    required this.resultJson,
    this.processingMs,
    this.videoFile,
    this.hints,
  });

  @override
  State<AnalysisViewPage> createState() => _AnalysisViewPageState();
}

class _AnalysisViewPageState extends State<AnalysisViewPage>
    with TickerProviderStateMixin {
  late final List<_FrameData> _frames;
  late final TabController _tabCtrl;

  VideoPlayerController? _videoCtrl;
  bool _videoReady = false;

  int _currentFrame = 0;
  bool _isPlaying = false;
  /// Timestamp of the last manual seek. The video-position listener ignores
  /// updates for 300 ms after a seek so the arrows always land on exactly the
  /// requested frame.
  DateTime? _lastManualSeek;

  // ── Shared scroll controller (given to _SkeletonTab so we can
  //    scroll to top when a timecode link is tapped) ─────────────
  final ScrollController _skeletonScrollCtrl = ScrollController();

  @override
  void initState() {
    super.initState();
    _tabCtrl = TabController(length: 3, vsync: this);

    final parsed = jsonDecode(widget.resultJson) as Map<String, dynamic>;
    _frames = ((parsed['frames'] as List?) ?? [])
        .cast<Map<String, dynamic>>()
        .map(_FrameData.fromJson)
        .toList();

    if (widget.videoFile != null) {
      _videoCtrl = VideoPlayerController.file(widget.videoFile!)
        ..initialize().then((_) async {
          if (mounted) {
            // Mute: the user is viewing the skeleton overlay, not watching the film
            await _videoCtrl!.setVolume(0);
            setState(() => _videoReady = true);
            // Listen to video position changes to keep skeleton in sync
            _videoCtrl!.addListener(_onVideoPositionChanged);
          }
        });
    }
  }

  /// Called on every video frame tick; maps the current playback position
  /// to the closest analysis frame so the skeleton overlay stays in sync.
  void _onVideoPositionChanged() {
    if (!mounted || _videoCtrl == null) return;
    // Ignore ticks for 300 ms after a manual seek so the arrows don't drift.
    if (_lastManualSeek != null &&
        DateTime.now().difference(_lastManualSeek!).inMilliseconds < 300) {
      return;
    }
    // Add a small lookahead to compensate for the decoder pipeline delay
    // (video_player reports the last decoded frame, not the currently displayed one).
    const kLookaheadMs =
        100; // IMPORTANT: c'est ce qui rend parfait le calage entre vidéo et squelette, si tu baisse le squelette a du retard par rapport à la vidéo, si tu l'augmente le squelette est en avance sur la vidéo. 100ms semble être un bon compromis pour compenser le délai de décodage sans introduire de lag perceptible.
    final posMs = _videoCtrl!.value.position.inMilliseconds + kLookaheadMs;

    // Binary search for the last frame whose timestamp ≤ posMs (floor)
    int lo = 0, hi = _frames.length - 1, floor = 0;
    while (lo <= hi) {
      final mid = (lo + hi) ~/ 2;
      if (_frames[mid].timestampMs <= posMs) {
        floor = mid;
        lo = mid + 1;
      } else {
        hi = mid - 1;
      }
    }

    // Pick the nearest frame (floor vs floor+1) to avoid systematic 1-frame lag
    int best = floor;
    if (floor + 1 < _frames.length) {
      final distFloor = posMs - _frames[floor].timestampMs;
      final distNext = _frames[floor + 1].timestampMs - posMs;
      if (distNext < distFloor) best = floor + 1;
    }

    final isNowPlaying = _videoCtrl!.value.isPlaying;
    if (best != _currentFrame || isNowPlaying != _isPlaying) {
      setState(() {
        _currentFrame = best;
        _isPlaying = isNowPlaying;
      });
    }
  }

  @override
  void dispose() {
    _videoCtrl?.removeListener(_onVideoPositionChanged);
    _skeletonScrollCtrl.dispose();
    _tabCtrl.dispose();
    _videoCtrl?.dispose();
    super.dispose();
  }

  /// Seek the video to the timestamp of [frameIndex] without playing.
  void _seekVideoToFrame(int frameIndex) {
    if (_videoCtrl == null || !_videoReady) return;
    if (frameIndex < 0 || frameIndex >= _frames.length) return;
    _lastManualSeek = DateTime.now();
    final ms = _frames[frameIndex].timestampMs;
    _videoCtrl!.seekTo(Duration(milliseconds: ms));
  }

  void _play() {
    if (_frames.isEmpty) return;
    _videoCtrl?.play();
    // _isPlaying is updated via the listener; no manual frame loop needed
  }

  @override
  Widget build(BuildContext context) {
    final accent = Theme.of(context).colorScheme.secondary;

    return Scaffold(
      backgroundColor: const Color(0xFF0D1B2A),
      appBar: AppBar(
        backgroundColor: const Color(0xFF0D1B2A),
        foregroundColor: Colors.white,
        title: const Text(
          'Visualisation',
          style: TextStyle(fontWeight: FontWeight.bold),
        ),
        bottom: TabBar(
          controller: _tabCtrl,
          indicatorColor: accent,
          labelColor: accent,
          unselectedLabelColor: Colors.grey,
          tabs: const [
            Tab(icon: Icon(Icons.person_outline), text: 'Squelette'),
            Tab(icon: Icon(Icons.show_chart), text: 'Angles'),
            Tab(icon: Icon(Icons.analytics_outlined), text: 'Stats'),
          ],
        ),
      ),
      body: _frames.isEmpty
          ? const Center(
              child: Text(
                'Aucune donnée disponible',
                style: TextStyle(color: Colors.white54),
              ),
            )
          : TabBarView(
              controller: _tabCtrl,
              children: [
                _SkeletonTab(
                  frames: _frames,
                  currentIndex: _currentFrame,
                  isPlaying: _isPlaying,
                  accent: accent,
                  videoCtrl: _videoCtrl,
                  videoReady: _videoReady,
                  hints: widget.hints,
                  onFrameChanged: (i) {
                    setState(() => _currentFrame = i);
                    _seekVideoToFrame(i);
                  },
                  onPlay: _play,
                  onPause: () {
                    _videoCtrl?.pause();
                    setState(() => _isPlaying = false);
                  },
                  onReset: () {
                    _videoCtrl?.pause();
                    _seekVideoToFrame(0);
                    setState(() {
                      _isPlaying = false;
                      _currentFrame = 0;
                    });
                  },
                  onSeekToMs: (ms) {
                    _lastManualSeek = DateTime.now();
                    _videoCtrl?.seekTo(Duration(milliseconds: ms));
                    // Scroll back to the top so the user sees the video jump
                    if (_skeletonScrollCtrl.hasClients) {
                      _skeletonScrollCtrl.animateTo(
                        0,
                        duration: const Duration(milliseconds: 400),
                        curve: Curves.easeInOut,
                      );
                    }
                    // Sync skeleton to nearest frame
                    int lo = 0, hi = _frames.length - 1, best = 0;
                    while (lo <= hi) {
                      final mid = (lo + hi) ~/ 2;
                      if (_frames[mid].timestampMs <= ms) {
                        best = mid;
                        lo = mid + 1;
                      } else {
                        hi = mid - 1;
                      }
                    }
                    setState(() => _currentFrame = best);
                  },
                  scrollController: _skeletonScrollCtrl,
                ),
                _AngleChartTab(frames: _frames, accent: accent),
                _StatsTab(
                  frames: _frames,
                  processingMs: widget.processingMs,
                  accent: accent,
                ),
              ],
            ),
    );
  }
}

// ─── Tab 1 — Skeleton viewer ────────────────────────────────────
class _SkeletonTab extends StatefulWidget {
  final List<_FrameData> frames;
  final int currentIndex;
  final bool isPlaying;
  final Color accent;
  final VideoPlayerController? videoCtrl;
  final bool videoReady;
  final ValueChanged<int> onFrameChanged;
  final VoidCallback onPlay;
  final VoidCallback onPause;
  final VoidCallback onReset;
  /// Optional markdown coaching hints shown in a scrollable panel below the
  /// video controls. Null when hints are not yet available.
  final String? hints;
  /// Called when the user taps a timecode link in the hints panel.
  final void Function(int ms)? onSeekToMs;
  /// External scroll controller — lets the parent scroll this tab to the top
  /// (e.g. after a timecode tap so the user sees the video jump).
  final ScrollController? scrollController;

  const _SkeletonTab({
    required this.frames,
    required this.currentIndex,
    required this.isPlaying,
    required this.accent,
    required this.onFrameChanged,
    required this.onPlay,
    required this.onPause,
    required this.onReset,
    this.videoCtrl,
    this.videoReady = false,
    this.hints,
    this.onSeekToMs,
    this.scrollController,
  });

  @override
  State<_SkeletonTab> createState() => _SkeletonTabState();
}

class _SkeletonTabState extends State<_SkeletonTab> {
  bool _showAngles = true;

  @override
  Widget build(BuildContext context) {
    final frame = widget.frames[widget.currentIndex];
    final hasVideo = widget.videoCtrl != null && widget.videoReady;
    final hasHints = widget.hints != null && widget.hints!.trim().isNotEmpty;

    // Constrain the video to at most 45 % of the screen height.
    final double maxVideoHeight = MediaQuery.of(context).size.height * 0.45;

    // We always use a single CustomScrollView so that:
    //  - the video section has a well-defined size via AspectRatio inside a
    //    SliverToBoxAdapter (no unbounded-height issues),
    //  - hints (when present) scroll naturally below the controls.
    return CustomScrollView(
      controller: widget.scrollController,
      slivers: [
        // ── Video + skeleton overlay ──────────────────────────────
        SliverToBoxAdapter(
          child: Padding(
            padding: const EdgeInsets.all(12),
            child: LimitedBox(
              maxHeight: maxVideoHeight,
              child: ClipRRect(
                borderRadius: BorderRadius.circular(16),
                child: Container(
                  color: const Color(0xFF0D1B2A),
                  child: hasVideo
                      ? _VideoWithOverlay(
                          ctrl: widget.videoCtrl!,
                          frame: frame,
                          accent: widget.accent,
                          showAngles: _showAngles,
                        )
                      : CustomPaint(
                          painter: _SkeletonPainter(
                            frame: frame,
                            accent: widget.accent,
                            fullFrame: false,
                            showAngles: _showAngles,
                          ),
                          child: const SizedBox.expand(),
                        ),
                ),
              ),
            ),
          ),
        ),

        // ── Frame info + angles toggle ────────────────────────────
        SliverToBoxAdapter(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
            child: Row(
              children: [
                SizedBox(
                  width: 70,
                  child: Text(
                    'Frame ${frame.frameIndex}',
                    style: const TextStyle(color: Colors.white54, fontSize: 12),
                  ),
                ),
                Expanded(
                  child: Text(
                    _fmtMs(frame.timestampMs),
                    textAlign: TextAlign.center,
                    style: const TextStyle(
                      color: Colors.white70,
                      fontSize: 13,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
                GestureDetector(
                  onTap: () => setState(() => _showAngles = !_showAngles),
                  child: AnimatedContainer(
                    duration: const Duration(milliseconds: 200),
                    padding: const EdgeInsets.symmetric(
                      horizontal: 10,
                      vertical: 5,
                    ),
                    decoration: BoxDecoration(
                      color: _showAngles
                          ? widget.accent.withValues(alpha: 0.18)
                          : Colors.white10,
                      borderRadius: BorderRadius.circular(20),
                      border: Border.all(
                        color: _showAngles ? widget.accent : Colors.white24,
                        width: 1,
                      ),
                    ),
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Icon(
                          Icons.straighten_rounded,
                          size: 13,
                          color:
                              _showAngles ? widget.accent : Colors.white38,
                        ),
                        const SizedBox(width: 5),
                        Text(
                          'Angles',
                          style: TextStyle(
                            fontSize: 12,
                            color:
                                _showAngles ? widget.accent : Colors.white38,
                            fontWeight: _showAngles
                                ? FontWeight.bold
                                : FontWeight.normal,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),

        // ── Scrubber ─────────────────────────────────────────────
        SliverToBoxAdapter(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 12),
            child: SliderTheme(
              data: SliderTheme.of(context).copyWith(
                activeTrackColor: widget.accent,
                thumbColor: widget.accent,
                inactiveTrackColor: Colors.white12,
                overlayColor: widget.accent.withValues(alpha: 0.2),
                trackHeight: 3,
                thumbShape:
                    const RoundSliderThumbShape(enabledThumbRadius: 8),
              ),
              child: Slider(
                min: 0,
                max: (widget.frames.length - 1).toDouble(),
                value: widget.currentIndex.toDouble(),
                onChanged: (v) => widget.onFrameChanged(v.round()),
              ),
            ),
          ),
        ),

        // ── Playback controls ─────────────────────────────────────
        SliverToBoxAdapter(
          child: Padding(
            padding: const EdgeInsets.only(bottom: 12, top: 4),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                IconButton(
                  onPressed: widget.onReset,
                  icon: const Icon(
                    Icons.skip_previous_rounded,
                    color: Colors.white70,
                  ),
                  iconSize: 32,
                ),
                const SizedBox(width: 8),
                IconButton(
                  onPressed: widget.currentIndex > 0
                      ? () => widget.onFrameChanged(widget.currentIndex - 1)
                      : null,
                  icon: const Icon(
                    Icons.chevron_left_rounded,
                    color: Colors.white70,
                  ),
                  iconSize: 36,
                ),
                const SizedBox(width: 8),
                GestureDetector(
                  onTap: widget.isPlaying ? widget.onPause : widget.onPlay,
                  child: Container(
                    width: 52,
                    height: 52,
                    decoration: BoxDecoration(
                      color: widget.accent,
                      shape: BoxShape.circle,
                    ),
                    child: Icon(
                      widget.isPlaying
                          ? Icons.pause_rounded
                          : Icons.play_arrow_rounded,
                      color: Colors.black,
                      size: 30,
                    ),
                  ),
                ),
                const SizedBox(width: 8),
                IconButton(
                  onPressed: widget.currentIndex < widget.frames.length - 1
                      ? () => widget.onFrameChanged(widget.currentIndex + 1)
                      : null,
                  icon: const Icon(
                    Icons.chevron_right_rounded,
                    color: Colors.white70,
                  ),
                  iconSize: 36,
                ),
                const SizedBox(width: 8),
                IconButton(
                  onPressed: () =>
                      widget.onFrameChanged(widget.frames.length - 1),
                  icon: const Icon(
                    Icons.skip_next_rounded,
                    color: Colors.white70,
                  ),
                  iconSize: 32,
                ),
              ],
            ),
          ),
        ),

        // ── Coaching hints (only when available) ─────────────────
        if (hasHints) ...[
          SliverToBoxAdapter(
            child: Padding(
              padding: const EdgeInsets.fromLTRB(16, 4, 16, 4),
              child: Row(
                children: [
                  Icon(
                    Icons.tips_and_updates_rounded,
                    color: widget.accent,
                    size: 18,
                  ),
                  const SizedBox(width: 8),
                  Text(
                    'Conseils IA',
                    style: TextStyle(
                      color: widget.accent,
                      fontSize: 15,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ],
              ),
            ),
          ),
          const SliverToBoxAdapter(
            child: Divider(
              color: Colors.white12,
              height: 1,
              indent: 16,
              endIndent: 16,
            ),
          ),
          SliverToBoxAdapter(
            child: _HintsView(
              hintsMarkdown: _preprocessHints(widget.hints!),
              accent: widget.accent,
              onSeekToMs: widget.onSeekToMs ?? (_) {},
            ),
          ),
        ],
      ],
    );
  }

  String _fmtMs(int ms) {
    final s = ms ~/ 1000;
    final m = s ~/ 60;
    return '${m.toString().padLeft(2, '0')}:${(s % 60).toString().padLeft(2, '0')}';
  }
}

// ─── Video + skeleton overlay widget ────────────────────────────
class _VideoWithOverlay extends StatelessWidget {
  final VideoPlayerController ctrl;
  final _FrameData frame;
  final Color accent;
  final bool showAngles;

  const _VideoWithOverlay({
    required this.ctrl,
    required this.frame,
    required this.accent,
    this.showAngles = true,
  });

  @override
  Widget build(BuildContext context) {
    final aspectRatio = ctrl.value.aspectRatio;
    return Center(
      child: ClipRRect(
        borderRadius: BorderRadius.circular(16),
        child: AspectRatio(
          aspectRatio: aspectRatio,
          child: Stack(
            fit: StackFit.expand,
            children: [
              // ── Video layer ──
              VideoPlayer(ctrl),

            // ── Semi-transparent dark veil to make skeleton visible ──
            Container(color: Colors.black.withValues(alpha: 0.25)),

            // ── Skeleton overlay — ignores pointer so video gestures work ──
            IgnorePointer(
              child: CustomPaint(
                painter: _SkeletonPainter(
                  frame: frame,
                  accent: accent,
                  fullFrame: true,
                  showAngles: showAngles,
                ),
              ),
            ),
          ],
        ),
        ),
      ),
    );
  }
}

// ─── Skeleton CustomPainter ──────────────────────────────────────
class _SkeletonPainter extends CustomPainter {
  final _FrameData frame;
  final Color accent;

  /// When true, landmarks (already normalised 0-1 by MediaPipe) are mapped
  /// directly to pixel coordinates: x*width, y*height.  This is the correct
  /// mode when painting over a video that fills the full canvas.
  /// When false (no video), use auto-fit bounding-box centering.
  final bool fullFrame;

  /// Whether to render the degree labels next to each joint.
  final bool showAngles;

  const _SkeletonPainter({
    required this.frame,
    required this.accent,
    this.fullFrame = false,
    this.showAngles = true,
  });

  @override
  void paint(Canvas canvas, Size size) {
    if (!frame.poseDetected || frame.landmarks.isEmpty) {
      if (!fullFrame) {
        final tp = TextPainter(
          text: const TextSpan(
            text: 'Aucune pose détectée',
            style: TextStyle(color: Colors.white38, fontSize: 14),
          ),
          textDirection: TextDirection.ltr,
        )..layout();
        tp.paint(
          canvas,
          Offset(
            size.width / 2 - tp.width / 2,
            size.height / 2 - tp.height / 2,
          ),
        );
      }
      return;
    }

    // Build the mapping function depending on mode
    final Offset Function(Offset) toCanvas;

    if (fullFrame) {
      // Direct mapping: MediaPipe normalized coords → pixel on the video rect
      toCanvas = (norm) => Offset(norm.dx * size.width, norm.dy * size.height);
    } else {
      // Auto-fit bounding box so skeleton is centered on a blank canvas
      final xs = frame.landmarks.values.map((o) => o.dx).toList();
      final ys = frame.landmarks.values.map((o) => o.dy).toList();
      final minX = xs.reduce(math.min);
      final maxX = xs.reduce(math.max);
      final minY = ys.reduce(math.min);
      final maxY = ys.reduce(math.max);
      final rangeX = (maxX - minX).clamp(0.01, 1.0);
      final rangeY = (maxY - minY).clamp(0.01, 1.0);
      const padding = 48.0;
      final drawW = size.width - padding * 2;
      final drawH = size.height - padding * 2;
      final scale = math.min(drawW / rangeX, drawH / rangeY);
      final offsetX = padding + (drawW - rangeX * scale) / 2;
      final offsetY = padding + (drawH - rangeY * scale) / 2;
      toCanvas = (norm) => Offset(
        offsetX + (norm.dx - minX) * scale,
        offsetY + (norm.dy - minY) * scale,
      );
    }

    // ── Connections ──
    final bonePaint = Paint()
      ..color = accent.withValues(alpha: 0.85)
      ..strokeWidth = fullFrame ? 3.5 : 2.5
      ..style = PaintingStyle.stroke
      ..strokeCap = StrokeCap.round;

    for (final (a, b) in _LM.connections) {
      final pA = frame.landmarks[a];
      final pB = frame.landmarks[b];
      if (pA == null || pB == null) continue;
      canvas.drawLine(toCanvas(pA), toCanvas(pB), bonePaint);
    }

    // ── Joints ──
    final jointPaint = Paint()
      ..color = Colors.white
      ..style = PaintingStyle.fill;
    final jointOutline = Paint()
      ..color = accent
      ..strokeWidth = 1.5
      ..style = PaintingStyle.stroke;

    for (final entry in frame.landmarks.entries) {
      final pt = toCanvas(entry.value);
      canvas.drawCircle(pt, 5, jointPaint);
      canvas.drawCircle(pt, 5, jointOutline);
    }

    // ── Angle labels for all detected joints (optional) ──
    if (!showAngles) return;
    for (final entry in frame.angles.entries) {
      final jointId = entry.key;
      final angle = entry.value;
      final jointPos = frame.landmarks[jointId];
      if (jointPos == null) continue;

      final pt = toCanvas(jointPos);
      final label = '${angle.toStringAsFixed(0)}°';

      final tp = TextPainter(
        text: TextSpan(
          text: label,
          style: TextStyle(
            color: accent,
            fontSize: fullFrame ? 11 : 10,
            fontWeight: FontWeight.bold,
          ),
        ),
        textDirection: TextDirection.ltr,
      )..layout();

      // Background pill
      final rect = RRect.fromRectAndRadius(
        Rect.fromLTWH(pt.dx + 8, pt.dy - 10, tp.width + 8, tp.height + 4),
        const Radius.circular(6),
      );
      canvas.drawRRect(
        rect,
        Paint()..color = const Color(0xFF162032).withValues(alpha: 0.85),
      );
      tp.paint(canvas, Offset(pt.dx + 12, pt.dy - 8));
    }
  }

  @override
  bool shouldRepaint(_SkeletonPainter old) =>
      old.frame != frame ||
      old.showAngles != showAngles ||
      old.accent != accent;
}

// ─── Tab 2 — Angle chart ────────────────────────────────────────

/// All joints for which we compute angles, in display order.
const _kAngleJoints = <int, String>{
  _LM.lElbow: 'Coude G',
  _LM.rElbow: 'Coude D',
  _LM.lShoulder: 'Épaule G',
  _LM.rShoulder: 'Épaule D',
  _LM.lHip: 'Hanche G',
  _LM.rHip: 'Hanche D',
  _LM.lKnee: 'Genou G',
  _LM.rKnee: 'Genou D',
};

/// Distinct colors per joint so curves are easy to differentiate.
const _kJointColors = <int, Color>{
  _LM.lElbow: Color(0xFF64B5F6), // blue 300
  _LM.rElbow: Color(0xFFFFB74D), // orange 300
  _LM.lShoulder: Color(0xFF81C784), // green 300
  _LM.rShoulder: Color(0xFFE57373), // red 300
  _LM.lHip: Color(0xFFCE93D8), // purple 200
  _LM.rHip: Color(0xFF4DB6AC), // teal 300
  _LM.lKnee: Color(0xFFFFF176), // yellow 200
  _LM.rKnee: Color(0xFFFF8A65), // deep orange 300
};

class _AngleChartTab extends StatefulWidget {
  final List<_FrameData> frames;
  final Color accent;
  const _AngleChartTab({required this.frames, required this.accent});

  @override
  State<_AngleChartTab> createState() => _AngleChartTabState();
}

class _AngleChartTabState extends State<_AngleChartTab> {
  /// Which joints are currently shown on the chart.
  late final Set<int> _visible;

  @override
  void initState() {
    super.initState();
    // Start with elbows visible; user can toggle the rest
    _visible = {_LM.lElbow, _LM.rElbow};
  }

  List<FlSpot> _spots(int jointId) {
    final spots = <FlSpot>[];
    for (final f in widget.frames) {
      final angle = f.angles[jointId];
      if (angle != null) {
        spots.add(FlSpot(f.timestampMs / 1000.0, angle));
      }
    }
    return spots;
  }

  @override
  Widget build(BuildContext context) {
    // Precompute spots for visible joints that actually have data
    final seriesData = <int, List<FlSpot>>{};
    for (final id in _kAngleJoints.keys) {
      final s = _spots(id);
      if (s.isNotEmpty) seriesData[id] = s;
    }

    final visibleSeries = seriesData.entries
        .where((e) => _visible.contains(e.key))
        .toList();

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _SectionTitle('Angles articulaires', accent: widget.accent),
          const SizedBox(height: 12),

          // ── Joint selector chips ──
          Wrap(
            spacing: 8,
            runSpacing: 8,
            children: _kAngleJoints.entries.map((e) {
              final id = e.key;
              final hasData = seriesData.containsKey(id);
              final selected = _visible.contains(id) && hasData;
              final color = _kJointColors[id] ?? widget.accent;
              return FilterChip(
                label: Text(
                  e.value,
                  style: TextStyle(
                    fontSize: 11,
                    color: selected ? Colors.black : Colors.white60,
                  ),
                ),
                selected: selected,
                onSelected: hasData
                    ? (v) => setState(() {
                        if (v) {
                          _visible.add(id);
                        } else {
                          _visible.remove(id);
                        }
                      })
                    : null,
                selectedColor: color,
                backgroundColor: const Color(0xFF1E3050),
                checkmarkColor: Colors.black,
                side: BorderSide(
                  color: hasData
                      ? color.withValues(alpha: 0.6)
                      : Colors.white12,
                ),
                padding: const EdgeInsets.symmetric(horizontal: 4),
              );
            }).toList(),
          ),
          const SizedBox(height: 16),

          // ── Chart ──
          if (visibleSeries.isEmpty)
            _EmptyCard('Sélectionnez au moins une articulation')
          else
            _ChartCard(
              child: LineChart(
                LineChartData(
                  backgroundColor: const Color(0xFF162032),
                  gridData: FlGridData(
                    show: true,
                    getDrawingHorizontalLine: (_) =>
                        FlLine(color: Colors.white10, strokeWidth: 1),
                    getDrawingVerticalLine: (_) =>
                        FlLine(color: Colors.white10, strokeWidth: 1),
                  ),
                  borderData: FlBorderData(show: false),
                  titlesData: FlTitlesData(
                    leftTitles: AxisTitles(
                      axisNameWidget: const Text(
                        'Angle (°)',
                        style: TextStyle(color: Colors.white54, fontSize: 11),
                      ),
                      sideTitles: SideTitles(
                        showTitles: true,
                        reservedSize: 40,
                        getTitlesWidget: (v, _) => Text(
                          '${v.toInt()}°',
                          style: const TextStyle(
                            color: Colors.white38,
                            fontSize: 10,
                          ),
                        ),
                      ),
                    ),
                    bottomTitles: AxisTitles(
                      axisNameWidget: const Text(
                        'Temps (s)',
                        style: TextStyle(color: Colors.white54, fontSize: 11),
                      ),
                      sideTitles: SideTitles(
                        showTitles: true,
                        reservedSize: 28,
                        getTitlesWidget: (v, _) => Text(
                          '${v.toStringAsFixed(0)}s',
                          style: const TextStyle(
                            color: Colors.white38,
                            fontSize: 10,
                          ),
                        ),
                      ),
                    ),
                    topTitles: const AxisTitles(
                      sideTitles: SideTitles(showTitles: false),
                    ),
                    rightTitles: const AxisTitles(
                      sideTitles: SideTitles(showTitles: false),
                    ),
                  ),
                  lineBarsData: visibleSeries.map((e) {
                    final color = _kJointColors[e.key] ?? widget.accent;
                    return LineChartBarData(
                      spots: e.value,
                      isCurved: true,
                      color: color,
                      barWidth: 2,
                      dotData: const FlDotData(show: false),
                      belowBarData: BarAreaData(
                        show: true,
                        color: color.withValues(alpha: 0.06),
                      ),
                    );
                  }).toList(),
                  lineTouchData: LineTouchData(
                    touchTooltipData: LineTouchTooltipData(
                      getTooltipColor: (_) => const Color(0xFF1E3050),
                      getTooltipItems: (touchedSpots) => touchedSpots.map((s) {
                        final jointId = visibleSeries[s.barIndex].key;
                        final name = _kAngleJoints[jointId] ?? 'Joint $jointId';
                        return LineTooltipItem(
                          '$name\n${s.y.toStringAsFixed(1)}°',
                          TextStyle(
                            color: s.bar.color ?? Colors.white,
                            fontWeight: FontWeight.bold,
                            fontSize: 11,
                          ),
                        );
                      }).toList(),
                    ),
                  ),
                ),
              ),
            ),

          const SizedBox(height: 16),

          // ── Legend for visible series ──
          if (visibleSeries.isNotEmpty)
            Wrap(
              spacing: 16,
              runSpacing: 8,
              children: visibleSeries.map((e) {
                final color = _kJointColors[e.key] ?? widget.accent;
                final name = _kAngleJoints[e.key] ?? 'Joint ${e.key}';
                return _Legend(color: color, label: name);
              }).toList(),
            ),
        ],
      ),
    );
  }
}

// ─── Tab 3 — Stats ───────────────────────────────────────────────
class _StatsTab extends StatelessWidget {
  final List<_FrameData> frames;
  final int? processingMs;
  final Color accent;

  const _StatsTab({
    required this.frames,
    required this.processingMs,
    required this.accent,
  });

  /// Collect all angle values for [jointId] across all frames.
  List<double> _anglesFor(int jointId) => frames
      .expand((f) => f.angles.entries)
      .where((e) => e.key == jointId)
      .map((e) => e.value)
      .toList();

  @override
  Widget build(BuildContext context) {
    final detected = frames.where((f) => f.poseDetected).toList();
    final detRate = frames.isEmpty
        ? 0.0
        : detected.length / frames.length * 100;

    final durationMs = frames.isNotEmpty ? frames.last.timestampMs : 0;

    // Build stats for every joint that has data
    final jointStats = <int, ({double min, double max, double avg})>{};
    for (final id in _kAngleJoints.keys) {
      final vals = _anglesFor(id);
      if (vals.isNotEmpty) {
        final mn = vals.reduce(math.min);
        final mx = vals.reduce(math.max);
        final av = vals.reduce((a, b) => a + b) / vals.length;
        jointStats[id] = (min: mn, max: mx, avg: av);
      }
    }

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _SectionTitle('Résumé de la session', accent: accent),
          const SizedBox(height: 12),
          _StatCard(
            accent: accent,
            children: [
              _StatRow(
                'Durée analysée',
                _fmtMs(durationMs),
                icon: Icons.timer_outlined,
                accent: accent,
              ),
              _StatRow(
                'Frames analysées',
                '${frames.length}',
                icon: Icons.video_library_outlined,
                accent: accent,
              ),
              if (processingMs != null)
                _StatRow(
                  'Temps de traitement IA',
                  '${(processingMs! / 1000).toStringAsFixed(1)} s',
                  icon: Icons.memory_outlined,
                  accent: accent,
                ),
              _StatRow(
                'Taux de détection',
                '${detRate.toStringAsFixed(1)} %',
                icon: Icons.person_search_outlined,
                accent: accent,
                valueColor: detRate > 80
                    ? Colors.greenAccent
                    : detRate > 50
                    ? Colors.orangeAccent
                    : Colors.redAccent,
              ),
              _StatRow(
                'Articulations mesurées',
                '${jointStats.length} / ${_kAngleJoints.length}',
                icon: Icons.architecture_outlined,
                accent: accent,
              ),
            ],
          ),

          // ── Per-joint angle stats ──
          if (jointStats.isNotEmpty) ...[
            const SizedBox(height: 24),
            _SectionTitle('Angles par articulation', accent: accent),
            const SizedBox(height: 12),
            ...jointStats.entries.map((entry) {
              final id = entry.key;
              final s = entry.value;
              final name = _kAngleJoints[id] ?? 'Joint $id';
              final color = _kJointColors[id] ?? accent;
              return Padding(
                padding: const EdgeInsets.only(bottom: 12),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Container(
                          width: 10,
                          height: 10,
                          decoration: BoxDecoration(
                            color: color,
                            shape: BoxShape.circle,
                          ),
                        ),
                        const SizedBox(width: 8),
                        Text(
                          name,
                          style: TextStyle(
                            color: color,
                            fontWeight: FontWeight.bold,
                            fontSize: 13,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 6),
                    _StatCard(
                      accent: accent,
                      children: [
                        _StatRow(
                          'Minimum',
                          '${s.min.toStringAsFixed(1)}°',
                          icon: Icons.arrow_downward_rounded,
                          accent: accent,
                          valueColor: Colors.lightBlueAccent,
                        ),
                        _StatRow(
                          'Maximum',
                          '${s.max.toStringAsFixed(1)}°',
                          icon: Icons.arrow_upward_rounded,
                          accent: accent,
                          valueColor: Colors.orangeAccent,
                        ),
                        _StatRow(
                          'Moyenne',
                          '${s.avg.toStringAsFixed(1)}°',
                          icon: Icons.show_chart,
                          accent: accent,
                        ),
                        _StatRow(
                          'Amplitude',
                          '${(s.max - s.min).toStringAsFixed(1)}°',
                          icon: Icons.swap_vert_rounded,
                          accent: accent,
                        ),
                      ],
                    ),
                    const SizedBox(height: 6),
                    _AngleRangeBar(
                      min: s.min,
                      max: s.max,
                      avg: s.avg,
                      accent: color,
                    ),
                  ],
                ),
              );
            }),
          ],

          const SizedBox(height: 20),
          _SectionTitle('Landmarks détectés', accent: accent),
          const SizedBox(height: 12),
          _LandmarkHeatmap(frames: frames, accent: accent),
        ],
      ),
    );
  }

  String _fmtMs(int ms) {
    final s = ms ~/ 1000;
    final m = s ~/ 60;
    return '${m.toString().padLeft(2, '0')}:${(s % 60).toString().padLeft(2, '0')}';
  }
}

// ─── Shared widgets ──────────────────────────────────────────────

class _SectionTitle extends StatelessWidget {
  final String text;
  final Color accent;
  const _SectionTitle(this.text, {required this.accent});

  @override
  Widget build(BuildContext context) {
    return Text(
      text,
      style: TextStyle(
        color: accent,
        fontWeight: FontWeight.bold,
        fontSize: 15,
        letterSpacing: 0.3,
      ),
    );
  }
}

class _StatCard extends StatelessWidget {
  final List<Widget> children;
  final Color accent;
  const _StatCard({required this.children, required this.accent});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFF162032),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.white10),
      ),
      child: Column(children: children),
    );
  }
}

class _StatRow extends StatelessWidget {
  final String label;
  final String value;
  final IconData icon;
  final Color accent;
  final Color? valueColor;

  const _StatRow(
    this.label,
    this.value, {
    required this.icon,
    required this.accent,
    this.valueColor,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 6),
      child: Row(
        children: [
          Icon(icon, size: 16, color: accent.withValues(alpha: 0.7)),
          const SizedBox(width: 10),
          Expanded(
            child: Text(
              label,
              style: const TextStyle(color: Colors.white60, fontSize: 13),
            ),
          ),
          Text(
            value,
            style: TextStyle(
              fontWeight: FontWeight.bold,
              fontSize: 14,
              color: valueColor ?? Colors.white,
            ),
          ),
        ],
      ),
    );
  }
}

class _ChartCard extends StatelessWidget {
  final Widget child;
  const _ChartCard({required this.child});

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 240,
      padding: const EdgeInsets.fromLTRB(8, 16, 16, 8),
      decoration: BoxDecoration(
        color: const Color(0xFF162032),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.white10),
      ),
      child: child,
    );
  }
}

class _EmptyCard extends StatelessWidget {
  final String message;
  const _EmptyCard(this.message);

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 100,
      alignment: Alignment.center,
      decoration: BoxDecoration(
        color: const Color(0xFF162032),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.white10),
      ),
      child: Text(
        message,
        style: const TextStyle(color: Colors.white38, fontSize: 13),
      ),
    );
  }
}

class _Legend extends StatelessWidget {
  final Color color;
  final String label;
  const _Legend({required this.color, required this.label});

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Container(
          width: 20,
          height: 3,
          decoration: BoxDecoration(
            color: color,
            borderRadius: BorderRadius.circular(2),
          ),
        ),
        const SizedBox(width: 6),
        Text(
          label,
          style: const TextStyle(color: Colors.white60, fontSize: 12),
        ),
      ],
    );
  }
}

class _AngleRangeBar extends StatelessWidget {
  final double min;
  final double max;
  final double avg;
  final Color accent;

  const _AngleRangeBar({
    required this.min,
    required this.max,
    required this.avg,
    required this.accent,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFF162032),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.white10),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'Amplitude angulaire',
            style: TextStyle(color: Colors.white60, fontSize: 12),
          ),
          const SizedBox(height: 12),
          Row(
            children: [
              Text(
                '${min.toStringAsFixed(0)}°',
                style: const TextStyle(
                  color: Colors.lightBlueAccent,
                  fontSize: 11,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(width: 8),
              Expanded(
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(4),
                  child: Stack(
                    children: [
                      Container(height: 12, color: Colors.white10),
                      LayoutBuilder(
                        builder: (_, constraints) {
                          final total = math.max(max - min, 1.0);
                          final avgFrac = (avg - min) / total;
                          return CustomPaint(
                            size: Size(constraints.maxWidth, 12),
                            painter: _RangeBarPainter(
                              avgFrac: avgFrac,
                              accent: accent,
                            ),
                          );
                        },
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(width: 8),
              Text(
                '${max.toStringAsFixed(0)}°',
                style: const TextStyle(
                  color: Colors.orangeAccent,
                  fontSize: 11,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ),
          const SizedBox(height: 6),
          Center(
            child: Text(
              'Moy. ${avg.toStringAsFixed(1)}°',
              style: TextStyle(color: accent, fontSize: 11),
            ),
          ),
        ],
      ),
    );
  }
}

class _RangeBarPainter extends CustomPainter {
  final double avgFrac;
  final Color accent;
  const _RangeBarPainter({required this.avgFrac, required this.accent});
  @override
  void paint(Canvas canvas, Size size) {
    // Gradient bar
    final grad = LinearGradient(
      colors: [Colors.lightBlueAccent, accent, Colors.orangeAccent],
    );
    canvas.drawRect(
      Rect.fromLTWH(0, 0, size.width, size.height),
      Paint()
        ..shader = grad.createShader(
          Rect.fromLTWH(0, 0, size.width, size.height),
        ),
    );
    // Avg marker
    final x = avgFrac.clamp(0.0, 1.0) * size.width;
    canvas.drawRect(
      Rect.fromLTWH(x - 1.5, -2, 3, size.height + 4),
      Paint()..color = Colors.white,
    );
  }

  @override
  bool shouldRepaint(_RangeBarPainter old) =>
      old.avgFrac != avgFrac || old.accent != accent;
}

class _LandmarkHeatmap extends StatelessWidget {
  final List<_FrameData> frames;
  final Color accent;
  const _LandmarkHeatmap({required this.frames, required this.accent});

  @override
  Widget build(BuildContext context) {
    // Count how many frames each landmark appears in
    final counts = <int, int>{};
    for (final f in frames) {
      for (final id in f.landmarks.keys) {
        counts[id] = (counts[id] ?? 0) + 1;
      }
    }
    final total = frames.length.toDouble();

    final items = _LM.names.entries.toList()
      ..sort((a, b) => (counts[b.key] ?? 0).compareTo(counts[a.key] ?? 0));

    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: const Color(0xFF162032),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.white10),
      ),
      child: Column(
        children: items.map((e) {
          final count = counts[e.key] ?? 0;
          final pct = total == 0 ? 0.0 : count / total;

          return Padding(
            padding: const EdgeInsets.symmetric(vertical: 4),
            child: Row(
              children: [
                SizedBox(
                  width: 90,
                  child: Text(
                    e.value,
                    style: const TextStyle(color: Colors.white54, fontSize: 11),
                  ),
                ),
                Expanded(
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(3),
                    child: LinearProgressIndicator(
                      value: pct,
                      backgroundColor: Colors.white10,
                      valueColor: AlwaysStoppedAnimation(
                        pct > 0.8
                            ? Colors.greenAccent
                            : pct > 0.5
                            ? accent
                            : Colors.orangeAccent,
                      ),
                      minHeight: 7,
                    ),
                  ),
                ),
                const SizedBox(width: 8),
                SizedBox(
                  width: 36,
                  child: Text(
                    '${(pct * 100).toStringAsFixed(0)}%',
                    textAlign: TextAlign.right,
                    style: const TextStyle(
                      color: Colors.white60,
                      fontSize: 10,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }
}

// ─── Tab 1 (inline) — Coaching hints rendered below the video ────

/// Regex that matches timecode tokens of the form `[1234ms]` or `[1m23s]`.
/// Groups: 1 — raw ms, 2 — minutes, 3 — seconds.
final _kTimecodeRe = RegExp(
  r'\[(?:(\d+)ms|(\d+)m(\d+)s)\]',
  caseSensitive: false,
);

/// Also matches backtick-wrapped variants Gemini sometimes emits.
final _kBacktickTimecodeRe = RegExp(
  r'`(\[(?:\d+ms|\d+m\d+s)\])`',
  caseSensitive: false,
);

/// Convert a timecode regex match to milliseconds.
int _tcToMs(Match m) {
  if (m.group(1) != null) return int.parse(m.group(1)!);
  return (int.parse(m.group(2)!) * 60 + int.parse(m.group(3)!)) * 1000;
}

/// Format ms as MM:SS label.
String _msToLabel(int ms) {
  final s = ms ~/ 1000;
  final m = s ~/ 60;
  return '${m.toString().padLeft(2, '0')}:${(s % 60).toString().padLeft(2, '0')}';
}

/// Pre-process hints markdown: strip backtick-wrapped timecodes and convert
/// every `[Xms]` / `[XmYs]` to an inline markdown link `[⏱ MM:SS](timecode://ms)`.
String _preprocessHints(String raw) {
  var out = raw.replaceAllMapped(_kBacktickTimecodeRe, (m) => m.group(1)!);
  out = out.replaceAllMapped(_kTimecodeRe, (m) {
    final ms = _tcToMs(m);
    return '[⏱ ${_msToLabel(ms)}](timecode://$ms)';
  });
  return out;
}

class _HintsView extends StatelessWidget {
  final String hintsMarkdown;
  final Color accent;
  final void Function(int ms) onSeekToMs;

  const _HintsView({
    required this.hintsMarkdown,
    required this.accent,
    required this.onSeekToMs,
  });

  @override
  Widget build(BuildContext context) {
    // MarkdownBody is non-scrollable (unlike Markdown which is a ListView).
    // This is required here because _HintsView lives inside a SliverToBoxAdapter
    // inside a CustomScrollView — nesting a scrollable Markdown inside a sliver
    // causes "Vertical viewport was given unbounded height".
    return Padding(
      padding: const EdgeInsets.fromLTRB(16, 8, 16, 32),
      child: MarkdownBody(
        data: hintsMarkdown,
        selectable: false,
        styleSheet: _buildStyleSheet(context),
        onTapLink: (text, href, title) {
          if (href != null && href.startsWith('timecode://')) {
            final ms = int.tryParse(href.substring('timecode://'.length));
            if (ms != null) onSeekToMs(ms);
          }
        },
      ),
    );
  }

  MarkdownStyleSheet _buildStyleSheet(BuildContext context) {
    const bodyColor = Colors.white;
    const mutedColor = Color(0xFFB0BEC5);
    final codeBackground = const Color(0xFF1E3050);

    return MarkdownStyleSheet(
      p: const TextStyle(color: bodyColor, fontSize: 14, height: 1.6),
      h1: TextStyle(
        color: accent,
        fontSize: 20,
        fontWeight: FontWeight.bold,
        height: 1.4,
      ),
      h2: TextStyle(
        color: accent,
        fontSize: 17,
        fontWeight: FontWeight.bold,
        height: 1.4,
      ),
      h3: TextStyle(
        color: accent,
        fontSize: 15,
        fontWeight: FontWeight.w600,
        height: 1.4,
      ),
      strong: const TextStyle(
        color: Colors.white,
        fontWeight: FontWeight.bold,
      ),
      em: const TextStyle(color: mutedColor, fontStyle: FontStyle.italic),
      listBullet: TextStyle(color: accent, fontSize: 14),
      listIndent: 20,
      a: TextStyle(
        color: accent,
        decoration: TextDecoration.none,
        fontWeight: FontWeight.bold,
        fontSize: 13,
      ),
      code: TextStyle(
        color: accent,
        backgroundColor: codeBackground,
        fontSize: 13,
        fontFamily: 'monospace',
      ),
      codeblockDecoration: BoxDecoration(
        color: codeBackground,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: Colors.white10),
      ),
      blockquoteDecoration: BoxDecoration(
        color: const Color(0xFF162032),
        borderRadius: BorderRadius.circular(4),
        border: Border(
          left: BorderSide(color: accent, width: 3),
        ),
      ),
      blockquote: const TextStyle(color: mutedColor, fontSize: 13, height: 1.5),
      horizontalRuleDecoration: const BoxDecoration(
        border: Border(bottom: BorderSide(color: Colors.white12)),
      ),
    );
  }
}
