services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minIO
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: .env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  rabbitmq:
    image: rabbitmq:4.2.4-management
    container_name: rabbitMQ
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgresql:
    image: postgres:18
    container_name: postgreSQL
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ascension}"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: ./apps/server
    container_name: ascensionServer
    profiles:
      - prod
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - RUST_LOG=info
    depends_on:
      postgresql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  ai-worker:
    build: ./apps/ai
    container_name: aiWorker
    profiles:
      - prod
    environment:
      - RABBITMQ_DEFAULT_USER=ascension
      - RABBITMQ_DEFAULT_PASS=ascension
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_URL=amqp://ascension:ascension@localhost:5672

      - POSTGRES_HOST=postgresql
      - POSTGRES_USER=ascension
      - POSTGRES_PASSWORD=ascension
      - POSTGRES_DB=ascension
      - DB_URI=postgres://ascension:ascension@postgresql:5432/ascension

      - MINIO_ROOT_USER=ascension
      - MINIO_ROOT_PASSWORD=ascension
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_BUCKET=videos

      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=debug
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  minio_data:
  postgres_data:
  rabbitmq_data:
