services:
  server:
    image: ${IMAGE_PREFIX}/ascension-server:latest

  ai-worker:
    image: ${IMAGE_PREFIX}/ascension-ai:latest

  postgresql:
    image: ${IMAGE_PREFIX}/ascension-postgres:latest

