import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const supportedLocales = [Locale('fr'), Locale('en')];

  static const Map<String, Map<String, String>> _values = {
    'fr': {
      'nav.home': 'Accueil',
      'nav.upload': 'Upload',
      'nav.stats': 'Stats',
      'nav.profile': 'Profil',
      'nav.semanticLabel': 'Navigation {label}',
      'nav.currentTabHint': 'Onglet actuellement sélectionné',
      'nav.openTabHint': 'Double tapez pour ouvrir {label}',
      'home.description': 'Visualiser l\'invisible',
      'home.comingSoon': 'Accueil bientôt disponible !',
      'upload.title': 'Uploader une vidéo',
      'upload.description':
          'Filmez ou importez votre session pour une analyse détaillée',
      'stats.title': 'Statistiques',
      'stats.description': 'Analyse détaillée de vos performances',
      'profile.title': 'Profil',
      'settings.title': 'Paramètres',
      'settings.backend': 'Backend',
      'settings.backendUrl': 'URL du backend',
      'settings.backendHint': 'http://192.168.1.x:8080',
      'settings.backendHelper':
          'Adresse API utilisée par l’application mobile.',
      'settings.save': 'Enregistrer',
      'settings.music': 'Musique de fond',
      'settings.musicSubtitle': 'Joue la musique Ascension en boucle',
      'settings.accessibility': 'Accessibilité',
      'settings.accessibilitySubtitle':
          'Personnalisez lisibilité, mouvement, interactions et interruptions.',
      'settings.readingDisplay': 'Lecture et affichage',
      'settings.textSize': 'Taille du texte',
      'settings.textSizeHelp': 'Ajuste la taille de texte de toute l’app.',
      'settings.language': 'Langue de l’application',
      'settings.languageSubtitle':
          'Choisissez la langue de l’interface (français/anglais).',
      'settings.languageFr': 'Français',
      'settings.languageEn': 'English',
      'settings.highContrast': 'Mode contraste élevé',
      'settings.highContrastHelp':
          'Renforce les contrastes pour les textes et contrôles.',
      'settings.dyslexia': 'Profil dyslexie (espacement)',
      'settings.dyslexiaHelp':
          'Augmente interlignage et espacement des caractères.',
      'settings.readingSpeed': 'Vitesse lecture / playback',
      'settings.readingSpeedHelp':
          'Ajuste la vitesse recommandée des contenus guidés.',
      'settings.interactionComfort': 'Interaction et confort',
      'settings.reducedMotion': 'Réduire les animations',
      'settings.reducedMotionHelp':
          'Diminue fortement transitions et effets de mouvement.',
      'settings.simplifiedUi': 'Interface simplifiée',
      'settings.simplifiedUiHelp':
          'Affichage plus aéré pour réduire la charge cognitive.',
      'settings.captions': 'Sous-titres activés par défaut',
      'settings.captionsHelp':
          'Active les sous-titres dès qu’un média les propose.',
      'settings.hapticIntensity': 'Intensité des retours haptiques',
      'settings.hapticHelp':
          'Choisissez la force des vibrations de confirmation.',
      'settings.hapticOff': 'Off',
      'settings.hapticLight': 'Léger',
      'settings.hapticMedium': 'Moyen',
      'settings.hapticStrong': 'Fort',
      'settings.reducedInterruptions': 'Réduire les interruptions',
      'settings.reducedInterruptionsHelp':
          'Préférence pour regrouper/réduire les notifications.',
      'settings.preview': 'Aperçu immédiat',
      'settings.previewText':
          'Exemple de texte : votre expérience d’accessibilité est mise à jour en direct.',
      'settings.reset': 'Réinitialiser',
      'settings.savedUrl': 'URL du backend sauvegardée ✓',
      'settings.resetDone': 'Accessibilité réinitialisée ✓',
      'settings.resetAnnounce': 'Paramètres d’accessibilité réinitialisés',
      'common.settings': 'Paramètres',
      'common.logoAscension': 'Logo Ascension',
      'common.errorLabel': 'Erreur: {message}',
      'auth.requiredField': 'Champ requis',
      'auth.invalidEmail': 'Email invalide',
      'auth.passwordMin8': 'Minimum 8 caractères',
      'auth.connectionSuccess': 'Connexion réussie',
      'auth.registerSuccess': 'Compte créé avec succès',
      'auth.connectionErrorCredentials': 'Email ou mot de passe incorrect.',
      'auth.connectionErrorServer': 'Impossible de joindre le serveur.',
      'auth.connectionErrorGeneric': 'Une erreur est survenue. Réessayez.',
      'auth.login.title': 'Connexion',
      'auth.login.subtitle': 'Bienvenue !\nConnectez-vous pour continuer.',
      'auth.login.emailHelper': 'Entrez votre adresse email.',
      'auth.login.password': 'Mot de passe',
      'auth.login.passwordHelper': 'Minimum 8 caractères recommandé.',
      'auth.login.showPassword': 'Afficher le mot de passe',
      'auth.login.hidePassword': 'Masquer le mot de passe',
      'auth.login.submit': 'Se connecter',
      'auth.login.noAccount': 'Pas encore de compte ? ',
      'auth.login.register': 'S\'inscrire',
      'auth.register.title': 'Créer un compte',
      'auth.register.subtitle':
          'Rejoignez Ascension et commencez votre progression.',
      'auth.register.username': 'Nom d\'utilisateur',
      'auth.register.usernameMin3': 'Minimum 3 caractères',
      'auth.register.emailHelper': 'Entrez une adresse email valide.',
      'auth.register.password': 'Mot de passe',
      'auth.register.passwordHelper': 'Minimum 8 caractères.',
      'auth.register.confirmPassword': 'Confirmer le mot de passe',
      'auth.register.confirmPasswordHelper': 'Retapez le mot de passe.',
      'auth.register.showConfirmPassword':
          'Afficher le mot de passe de confirmation',
      'auth.register.hideConfirmPassword':
          'Masquer le mot de passe de confirmation',
      'auth.register.passwordMismatch':
          'Les mots de passe ne correspondent pas',
      'auth.register.submit': 'S\'inscrire',
      'auth.register.hasAccount': 'Déjà un compte ? ',
      'auth.register.login': 'Se connecter',
      'auth.register.errorConflict':
          'Cet email ou nom d\'utilisateur est déjà utilisé.',
      'stats.emptyTitle': 'Aucune analyse pour l\'instant',
      'stats.emptySubtitle':
          'Vos analyses apparaîtront ici après\nle traitement d\'une vidéo.',
      'stats.statusCompleted': 'Terminée',
      'stats.statusFailed': 'Échouée',
      'stats.view': 'Visualiser',
      'stats.frames': '{count} frames',
      'stats.detectedRate': '{rate} % détecté',
      'date.todayAt': 'Aujourd\'hui à {time}',
      'date.yesterdayAt': 'Hier à {time}',
      'date.at': '{day} à {time}',
      'date.full': '{date} à {time}',
      'date.day.monday': 'Lundi',
      'date.day.tuesday': 'Mardi',
      'date.day.wednesday': 'Mercredi',
      'date.day.thursday': 'Jeudi',
      'date.day.friday': 'Vendredi',
      'date.day.saturday': 'Samedi',
      'date.day.sunday': 'Dimanche',
      'date.dayShort.monday': 'Lun',
      'date.dayShort.tuesday': 'Mar',
      'date.dayShort.wednesday': 'Mer',
      'date.dayShort.thursday': 'Jeu',
      'date.dayShort.friday': 'Ven',
      'date.dayShort.saturday': 'Sam',
      'date.dayShort.sunday': 'Dim',
      'profile.logoutTitle': 'Déconnexion',
      'profile.logoutPrompt': 'Voulez-vous vous déconnecter ?',
      'profile.cancel': 'Annuler',
      'profile.defaultUser': 'Utilisateur',
      'profile.editProfile': 'Modifier le profil',
      'profile.globalStats': 'Statistiques globales',
      'profile.analyses': 'Analyses',
      'profile.successes': 'Réussies',
      'profile.detection': 'Détection',
      'profile.latestAnalyses': 'Dernières analyses',
      'profile.emptyTitle': 'Aucune analyse pour l\'instant',
      'profile.emptySubtitle': 'Uploadez une vidéo pour commencer.',
      'profile.analysisCompleted': 'Analyse terminée',
      'profile.analysisFailed': 'Analyse échouée',
      'profile.framesDetected': '{frames} frames · {rate}% détecté',
      'profile.logoutAction': 'Se déconnecter',
      'profile.save': 'Enregistrer',
      'profile.username': 'Nom d\'utilisateur',
      'video.announceSelected':
          'Vidéo sélectionnée. Vous pouvez lancer l\'analyse.',
      'video.announceUploading': 'Envoi de la vidéo en cours',
      'video.announceAnalysing': 'Analyse vidéo démarrée',
      'video.announceDone': 'Analyse terminée',
      'video.announceError': 'Une erreur est survenue pendant l\'analyse',
      'video.pickOrRecord': 'Sélectionnez ou filmez votre session',
      'video.record': 'Filmer',
      'video.import': 'Importer',
      'video.previewUnavailable': 'Aperçu non disponible sur bureau',
      'video.analyze': 'Analyser',
      'video.uploadingProgress': 'Envoi en cours… {progress} %',
      'video.remainingCalculating': 'calcul en cours…',
      'video.remainingSoon': 'bientôt…',
      'video.errorTitle': 'Une erreur est survenue',
      'video.errorUnknown': 'Erreur inconnue',
      'video.retry': 'Réessayer',
      'video.doneSuccess': 'Analyse terminée !',
      'video.doneFailed': 'Analyse échouée',
      'video.processingTime': 'Traitement : {seconds} s',
      'video.framesAnalyzed': '{count} frames analysées',
      'video.viewAnalysis': 'Visualiser l\'analyse',
      'video.analyzeAnother': 'Analyser une autre vidéo',
      'video.results': 'Résultats',
      'video.totalFrames': 'Frames totales',
      'video.poseDetected': 'Pose détectée',
      'video.tapHint': 'Double tapez pour {action} une vidéo',
      'video.generatingHints': 'Génération des conseils IA…',
      'video.analysisInProgress': 'Analyse en cours…',
      'video.generatingHintsSubtitle':
          'Ascension analyse votre session et rédige vos conseils personnalisés.',
      'video.analysisSubtitle': 'Ascension analyse votre session d\'escalade.',
      'video.tip': 'Astuce {index}',
      'video.promoBadge': '✦ MODE PREMIUM',
      'video.timeoutError':
          'L\'analyse a dépassé le délai d\'attente (10 min). Vérifiez l\'état du worker et réessayez.',
      'video.errorNotLoggedIn': 'Utilisateur non connecté',
      'video.promo.1': 'Le mode Premium réduit le temps d\'analyse de 3×.',
      'video.promo.2': 'Avec Premium, vos analyses passent en tête de file.',
      'video.promo.3': 'Passez au mode Premium pour seulement 20€/mois.',
      'video.promo.4':
          'Premium : accédez à tout l\'historique de vos sessions.',
      'video.promo.5':
          'Comparez vos sessions côte à côte avec le mode Premium.',
      'video.promo.6':
          'Premium débloque des statistiques avancées par groupe musculaire.',
      'video.promo.7':
          'Le saviez-vous ? Ascension détecte jusqu\'à 33 points du corps humain.',
      'video.promo.8':
          'Astuce : un bon éclairage améliore la précision des landmarks.',
      'video.promo.9': 'Votre progression est analysée image par image.',
      'video.promo.10':
          'Vos données sont stockées de façon sécurisée dans le cloud.',
      'video.promo.11':
          'Premium : partagez vos analyses avec votre coach en un tap.',
      'video.promo.12':
          'Premium : recevez des objectifs personnalisés chaque semaine.',
      'video.promo.13':
          'L\'IA Ascension apprend de chaque session pour mieux vous conseiller.',
      'analysis.title': 'Visualisation',
      'analysis.tabSkeleton': 'Squelette',
      'analysis.tabAngles': 'Angles',
      'analysis.tabStats': 'Stats',
      'analysis.emptyData': 'Aucune donnée disponible',
      'analysis.noPoseDetected': 'Aucune pose détectée',
      'analysis.frame': 'Frame',
      'analysis.aiTips': 'Conseils IA',
      'analysis.jointAngles': 'Angles articulaires',
      'analysis.selectAtLeastOneJoint':
          'Sélectionnez au moins une articulation',
      'analysis.angleAxis': 'Angle (°)',
      'analysis.timeAxis': 'Temps (s)',
      'analysis.jointFallback': 'Articulation {id}',
      'analysis.sessionSummary': 'Résumé de la session',
      'analysis.durationAnalyzed': 'Durée analysée',
      'analysis.framesAnalyzed': 'Frames analysées',
      'analysis.aiProcessingTime': 'Temps de traitement IA',
      'analysis.detectionRate': 'Taux de détection',
      'analysis.measuredJoints': 'Articulations mesurées',
      'analysis.anglesByJoint': 'Angles par articulation',
      'analysis.minimum': 'Minimum',
      'analysis.maximum': 'Maximum',
      'analysis.average': 'Moyenne',
      'analysis.averageShort': 'Moy.',
      'analysis.amplitude': 'Amplitude',
      'analysis.detectedLandmarks': 'Landmarks détectés',
      'analysis.angularAmplitude': 'Amplitude angulaire',
      'joint.leftElbow': 'Coude G',
      'joint.rightElbow': 'Coude D',
      'joint.leftShoulder': 'Épaule G',
      'joint.rightShoulder': 'Épaule D',
      'joint.leftHip': 'Hanche G',
      'joint.rightHip': 'Hanche D',
      'joint.leftKnee': 'Genou G',
      'joint.rightKnee': 'Genou D',
      'landmark.leftShoulder': 'Épaule G',
      'landmark.rightShoulder': 'Épaule D',
      'landmark.leftElbow': 'Coude G',
      'landmark.rightElbow': 'Coude D',
      'landmark.leftWrist': 'Poignet G',
      'landmark.rightWrist': 'Poignet D',
      'landmark.leftHip': 'Hanche G',
      'landmark.rightHip': 'Hanche D',
      'landmark.leftKnee': 'Genou G',
      'landmark.rightKnee': 'Genou D',
      'landmark.leftAnkle': 'Cheville G',
      'landmark.rightAnkle': 'Cheville D',
    },
    'en': {
      'nav.home': 'Home',
      'nav.upload': 'Upload',
      'nav.stats': 'Stats',
      'nav.profile': 'Profile',
      'nav.semanticLabel': 'Navigation {label}',
      'nav.currentTabHint': 'Currently selected tab',
      'nav.openTabHint': 'Double tap to open {label}',
      'home.description': 'Visualize the invisible',
      'home.comingSoon': 'Home coming soon!',
      'upload.title': 'Upload a video',
      'upload.description':
          'Record or import your session for detailed analysis',
      'stats.title': 'Statistics',
      'stats.description': 'Detailed analysis of your performance',
      'profile.title': 'Profile',
      'settings.title': 'Settings',
      'settings.backend': 'Backend',
      'settings.backendUrl': 'Backend URL',
      'settings.backendHint': 'http://192.168.1.x:8080',
      'settings.backendHelper': 'API endpoint used by the mobile app.',
      'settings.save': 'Save',
      'settings.music': 'Background music',
      'settings.musicSubtitle': 'Play Ascension music on loop',
      'settings.accessibility': 'Accessibility',
      'settings.accessibilitySubtitle':
          'Customize readability, motion, interactions and interruptions.',
      'settings.readingDisplay': 'Reading and display',
      'settings.textSize': 'Text size',
      'settings.textSizeHelp': 'Adjust text size across the whole app.',
      'settings.language': 'Application language',
      'settings.languageSubtitle':
          'Choose interface language (French/English).',
      'settings.languageFr': 'Français',
      'settings.languageEn': 'English',
      'settings.highContrast': 'High contrast mode',
      'settings.highContrastHelp':
          'Increase contrast for text and interactive controls.',
      'settings.dyslexia': 'Dyslexia profile (spacing)',
      'settings.dyslexiaHelp': 'Increase line height and character spacing.',
      'settings.readingSpeed': 'Reading / playback speed',
      'settings.readingSpeedHelp':
          'Adjust recommended speed for guided content.',
      'settings.interactionComfort': 'Interaction and comfort',
      'settings.reducedMotion': 'Reduce animations',
      'settings.reducedMotionHelp':
          'Strongly reduce transitions and motion effects.',
      'settings.simplifiedUi': 'Simplified interface',
      'settings.simplifiedUiHelp': 'Airier layout to reduce cognitive load.',
      'settings.captions': 'Captions enabled by default',
      'settings.captionsHelp':
          'Enable captions by default when media provides them.',
      'settings.hapticIntensity': 'Haptic feedback intensity',
      'settings.hapticHelp': 'Choose confirmation vibration strength.',
      'settings.hapticOff': 'Off',
      'settings.hapticLight': 'Light',
      'settings.hapticMedium': 'Medium',
      'settings.hapticStrong': 'Strong',
      'settings.reducedInterruptions': 'Reduce interruptions',
      'settings.reducedInterruptionsHelp':
          'Preference to group/reduce notifications.',
      'settings.preview': 'Live preview',
      'settings.previewText':
          'Sample text: your accessibility experience updates instantly.',
      'settings.reset': 'Reset',
      'settings.savedUrl': 'Backend URL saved ✓',
      'settings.resetDone': 'Accessibility reset ✓',
      'settings.resetAnnounce': 'Accessibility settings reset',
      'common.settings': 'Settings',
      'common.logoAscension': 'Ascension logo',
      'common.errorLabel': 'Error: {message}',
      'auth.requiredField': 'Required field',
      'auth.invalidEmail': 'Invalid email',
      'auth.passwordMin8': 'Minimum 8 characters',
      'auth.connectionSuccess': 'Signed in successfully',
      'auth.registerSuccess': 'Account created successfully',
      'auth.connectionErrorCredentials': 'Incorrect email or password.',
      'auth.connectionErrorServer': 'Unable to reach the server.',
      'auth.connectionErrorGeneric': 'An error occurred. Please try again.',
      'auth.login.title': 'Sign in',
      'auth.login.subtitle': 'Welcome!\nSign in to continue.',
      'auth.login.emailHelper': 'Enter your email address.',
      'auth.login.password': 'Password',
      'auth.login.passwordHelper': '8+ characters recommended.',
      'auth.login.showPassword': 'Show password',
      'auth.login.hidePassword': 'Hide password',
      'auth.login.submit': 'Sign in',
      'auth.login.noAccount': 'No account yet? ',
      'auth.login.register': 'Sign up',
      'auth.register.title': 'Create account',
      'auth.register.subtitle':
          'Join Ascension and start tracking your progression.',
      'auth.register.username': 'Username',
      'auth.register.usernameMin3': 'Minimum 3 characters',
      'auth.register.emailHelper': 'Enter a valid email address.',
      'auth.register.password': 'Password',
      'auth.register.passwordHelper': 'Minimum 8 characters.',
      'auth.register.confirmPassword': 'Confirm password',
      'auth.register.confirmPasswordHelper': 'Type your password again.',
      'auth.register.showConfirmPassword': 'Show confirmation password',
      'auth.register.hideConfirmPassword': 'Hide confirmation password',
      'auth.register.passwordMismatch': 'Passwords do not match',
      'auth.register.submit': 'Sign up',
      'auth.register.hasAccount': 'Already have an account? ',
      'auth.register.login': 'Sign in',
      'auth.register.errorConflict':
          'This email or username is already in use.',
      'stats.emptyTitle': 'No analysis yet',
      'stats.emptySubtitle':
          'Your analyses will appear here after\na video is processed.',
      'stats.statusCompleted': 'Completed',
      'stats.statusFailed': 'Failed',
      'stats.view': 'View',
      'stats.frames': '{count} frames',
      'stats.detectedRate': '{rate} % detected',
      'date.todayAt': 'Today at {time}',
      'date.yesterdayAt': 'Yesterday at {time}',
      'date.at': '{day} at {time}',
      'date.full': '{date} at {time}',
      'date.day.monday': 'Monday',
      'date.day.tuesday': 'Tuesday',
      'date.day.wednesday': 'Wednesday',
      'date.day.thursday': 'Thursday',
      'date.day.friday': 'Friday',
      'date.day.saturday': 'Saturday',
      'date.day.sunday': 'Sunday',
      'date.dayShort.monday': 'Mon',
      'date.dayShort.tuesday': 'Tue',
      'date.dayShort.wednesday': 'Wed',
      'date.dayShort.thursday': 'Thu',
      'date.dayShort.friday': 'Fri',
      'date.dayShort.saturday': 'Sat',
      'date.dayShort.sunday': 'Sun',
      'profile.logoutTitle': 'Sign out',
      'profile.logoutPrompt': 'Do you want to sign out?',
      'profile.cancel': 'Cancel',
      'profile.defaultUser': 'User',
      'profile.editProfile': 'Edit profile',
      'profile.globalStats': 'Global statistics',
      'profile.analyses': 'Analyses',
      'profile.successes': 'Successful',
      'profile.detection': 'Detection',
      'profile.latestAnalyses': 'Recent analyses',
      'profile.emptyTitle': 'No analysis yet',
      'profile.emptySubtitle': 'Upload a video to get started.',
      'profile.analysisCompleted': 'Analysis completed',
      'profile.analysisFailed': 'Analysis failed',
      'profile.framesDetected': '{frames} frames · {rate}% detected',
      'profile.logoutAction': 'Sign out',
      'profile.save': 'Save',
      'profile.username': 'Username',
      'video.announceSelected': 'Video selected. You can now start analysis.',
      'video.announceUploading': 'Uploading video in progress',
      'video.announceAnalysing': 'Video analysis started',
      'video.announceDone': 'Analysis completed',
      'video.announceError': 'An error occurred during analysis',
      'video.pickOrRecord': 'Select or record your session',
      'video.record': 'Record',
      'video.import': 'Import',
      'video.previewUnavailable': 'Preview unavailable on desktop',
      'video.analyze': 'Analyze',
      'video.uploadingProgress': 'Uploading… {progress} %',
      'video.remainingCalculating': 'calculating…',
      'video.remainingSoon': 'soon…',
      'video.errorTitle': 'An error occurred',
      'video.errorUnknown': 'Unknown error',
      'video.retry': 'Try again',
      'video.doneSuccess': 'Analysis complete!',
      'video.doneFailed': 'Analysis failed',
      'video.processingTime': 'Processing: {seconds} s',
      'video.framesAnalyzed': '{count} frames analyzed',
      'video.viewAnalysis': 'View analysis',
      'video.analyzeAnother': 'Analyze another video',
      'video.results': 'Results',
      'video.totalFrames': 'Total frames',
      'video.poseDetected': 'Pose detected',
      'video.tapHint': 'Double tap to {action} a video',
      'video.generatingHints': 'Generating AI tips…',
      'video.analysisInProgress': 'Analysis in progress…',
      'video.generatingHintsSubtitle':
          'Ascension analyzes your session and writes personalized guidance.',
      'video.analysisSubtitle': 'Ascension is analyzing your climbing session.',
      'video.tip': 'Tip {index}',
      'video.promoBadge': '✦ PREMIUM MODE',
      'video.timeoutError':
          'Analysis exceeded timeout (10 min). Check worker status and try again.',
      'video.errorNotLoggedIn': 'User not logged in',
      'video.promo.1': 'Premium mode reduces analysis time by 3×.',
      'video.promo.2':
          'With Premium, your analyses move to the front of queue.',
      'video.promo.3': 'Switch to Premium for only €20/month.',
      'video.promo.4': 'Premium: access your full session history.',
      'video.promo.5': 'Compare sessions side by side with Premium mode.',
      'video.promo.6': 'Premium unlocks advanced stats per muscle group.',
      'video.promo.7':
          'Did you know? Ascension can detect up to 33 body points.',
      'video.promo.8':
          'Tip: good lighting improves landmark detection accuracy.',
      'video.promo.9': 'Your progress is analyzed frame by frame.',
      'video.promo.10': 'Your data is securely stored in the cloud.',
      'video.promo.11': 'Premium: share analyses with your coach in one tap.',
      'video.promo.12': 'Premium: receive personalized weekly goals.',
      'video.promo.13':
          'Ascension AI learns from each session to guide you better.',
      'analysis.title': 'Visualization',
      'analysis.tabSkeleton': 'Skeleton',
      'analysis.tabAngles': 'Angles',
      'analysis.tabStats': 'Stats',
      'analysis.emptyData': 'No data available',
      'analysis.noPoseDetected': 'No pose detected',
      'analysis.frame': 'Frame',
      'analysis.aiTips': 'AI tips',
      'analysis.jointAngles': 'Joint angles',
      'analysis.selectAtLeastOneJoint': 'Select at least one joint',
      'analysis.angleAxis': 'Angle (°)',
      'analysis.timeAxis': 'Time (s)',
      'analysis.jointFallback': 'Joint {id}',
      'analysis.sessionSummary': 'Session summary',
      'analysis.durationAnalyzed': 'Analyzed duration',
      'analysis.framesAnalyzed': 'Analyzed frames',
      'analysis.aiProcessingTime': 'AI processing time',
      'analysis.detectionRate': 'Detection rate',
      'analysis.measuredJoints': 'Measured joints',
      'analysis.anglesByJoint': 'Angles by joint',
      'analysis.minimum': 'Minimum',
      'analysis.maximum': 'Maximum',
      'analysis.average': 'Average',
      'analysis.averageShort': 'Avg.',
      'analysis.amplitude': 'Amplitude',
      'analysis.detectedLandmarks': 'Detected landmarks',
      'analysis.angularAmplitude': 'Angular amplitude',
      'joint.leftElbow': 'Left elbow',
      'joint.rightElbow': 'Right elbow',
      'joint.leftShoulder': 'Left shoulder',
      'joint.rightShoulder': 'Right shoulder',
      'joint.leftHip': 'Left hip',
      'joint.rightHip': 'Right hip',
      'joint.leftKnee': 'Left knee',
      'joint.rightKnee': 'Right knee',
      'landmark.leftShoulder': 'Left shoulder',
      'landmark.rightShoulder': 'Right shoulder',
      'landmark.leftElbow': 'Left elbow',
      'landmark.rightElbow': 'Right elbow',
      'landmark.leftWrist': 'Left wrist',
      'landmark.rightWrist': 'Right wrist',
      'landmark.leftHip': 'Left hip',
      'landmark.rightHip': 'Right hip',
      'landmark.leftKnee': 'Left knee',
      'landmark.rightKnee': 'Right knee',
      'landmark.leftAnkle': 'Left ankle',
      'landmark.rightAnkle': 'Right ankle',
    },
  };

  String t(String key) {
    final code = locale.languageCode;
    return _values[code]?[key] ?? _values['fr']?[key] ?? key;
  }

  String tr(String key, Map<String, String> params) {
    String value = t(key);
    params.forEach((k, v) {
      value = value.replaceAll('{$k}', v);
    });
    return value;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any(
    (supported) => supported.languageCode == locale.languageCode,
  );

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}
