#!/usr/bin/env bash

FILES=$(git diff --cached --name-only --diff-filter=ACM)
if [ -z "$FILES" ]; then
    exit 0
fi

.github/scripts/reformat_code
#echo "$FILES" | xargs git add

for FILE in $FILES; do
    if [ -f "$FILE" ]; then
        git add "$FILE"
    fi
done

echo "✔ Files formatted and updated in commit."
